/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { StartServiceTO } from '../models';
/**
 * ServiceDefinitionControllerApi - axios parameter creator
 * @export
 */
export const ServiceDefinitionControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {StartServiceTO} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        startService: async (body: StartServiceTO, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling startService.');
            }
            const localVarPath = `/rest/servicedefinition`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ServiceDefinitionControllerApi - functional programming interface
 * @export
 */
export const ServiceDefinitionControllerApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {StartServiceTO} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async startService(body: StartServiceTO, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await ServiceDefinitionControllerApiAxiosParamCreator(configuration).startService(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * ServiceDefinitionControllerApi - factory interface
 * @export
 */
export const ServiceDefinitionControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {StartServiceTO} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        startService(body: StartServiceTO, options?: any): AxiosPromise<void> {
            return ServiceDefinitionControllerApiFp(configuration).startService(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ServiceDefinitionControllerApi - object-oriented interface
 * @export
 * @class ServiceDefinitionControllerApi
 * @extends {BaseAPI}
 */
export class ServiceDefinitionControllerApi extends BaseAPI {
    /**
     * 
     * @param {StartServiceTO} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ServiceDefinitionControllerApi
     */
    public startService(body: StartServiceTO, options?: any) {
        return ServiceDefinitionControllerApiFp(this.configuration).startService(body, options).then((request) => request(this.axios, this.basePath));
    }
}
