/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ButtonsTO
 */
export interface ButtonsTO {
    /**
     * 
     * @type {ButtonTO}
     * @memberof ButtonsTO
     */
    complete?: any;
    /**
     * 
     * @type {ButtonTO}
     * @memberof ButtonsTO
     */
    cancel?: any;
    /**
     * 
     * @type {ButtonTO}
     * @memberof ButtonsTO
     */
    statusPdf?: any;
}
