/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ConfigEntryTO
 */
export interface ConfigEntryTO {
    /**
     * 
     * @type {string}
     * @memberof ConfigEntryTO
     */
    key: any;
    /**
     * 
     * @type {string}
     * @memberof ConfigEntryTO
     */
    value: any;
}
