/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface FormTO
 */
export interface FormTO {
    /**
     * 
     * @type {string}
     * @memberof FormTO
     */
    key: any;
    /**
     * 
     * @type {string}
     * @memberof FormTO
     */
    description?: any;
    /**
     * 
     * @type {string}
     * @memberof FormTO
     */
    authorizedGroups?: any;
    /**
     * 
     * @type {ButtonsTO}
     * @memberof FormTO
     */
    buttons?: any;
    /**
     * 
     * @type {Array&lt;GroupTO&gt;}
     * @memberof FormTO
     */
    groups?: any;
}
