/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface FormFieldTO
 */
export interface FormFieldTO {
    /**
     * 
     * @type {string}
     * @memberof FormFieldTO
     */
    type: any;
    /**
     * 
     * @type {string}
     * @memberof FormFieldTO
     */
    key: any;
    /**
     * 
     * @type {string}
     * @memberof FormFieldTO
     */
    defaultValue?: any;
    /**
     * 
     * @type {string}
     * @memberof FormFieldTO
     */
    defaultValueField?: any;
    /**
     * 
     * @type {string}
     * @memberof FormFieldTO
     */
    label?: any;
    /**
     * 
     * @type {string}
     * @memberof FormFieldTO
     */
    prependIcon?: any;
    /**
     * 
     * @type {string}
     * @memberof FormFieldTO
     */
    tooltip?: any;
    /**
     * 
     * @type {string}
     * @memberof FormFieldTO
     */
    ext?: any;
    /**
     * 
     * @type {boolean}
     * @memberof FormFieldTO
     */
    multiple?: any;
    /**
     * 
     * @type {string}
     * @memberof FormFieldTO
     */
    description?: any;
    /**
     * 
     * @type {string}
     * @memberof FormFieldTO
     */
    ldapOus?: any;
    /**
     * 
     * @type {string}
     * @memberof FormFieldTO
     */
    imageHeight?: any;
    /**
     * 
     * @type {string}
     * @memberof FormFieldTO
     */
    imageWidth?: any;
    /**
     * 
     * @type {boolean}
     * @memberof FormFieldTO
     */
    readonly?: any;
    /**
     * 
     * @type {number}
     * @memberof FormFieldTO
     */
    rows?: any;
    /**
     * 
     * @type {number}
     * @memberof FormFieldTO
     */
    col?: any;
    /**
     * 
     * @type {Array&lt;ItemTO&gt;}
     * @memberof FormFieldTO
     */
    items?: any;
    /**
     * 
     * @type {Array&lt;RuleTO&gt;}
     * @memberof FormFieldTO
     */
    rules?: any;
    /**
     * 
     * @type {string}
     * @memberof FormFieldTO
     */
    itemText?: any;
    /**
     * 
     * @type {string}
     * @memberof FormFieldTO
     */
    itemValue?: any;
    /**
     * 
     * @type {boolean}
     * @memberof FormFieldTO
     */
    returnObject?: any;
}
