/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ProcessConfigTO
 */
export interface ProcessConfigTO {
    /**
     * 
     * @type {string}
     * @memberof ProcessConfigTO
     */
    key: any;
    /**
     * 
     * @type {Array&lt;StatusConfigTO&gt;}
     * @memberof ProcessConfigTO
     */
    statusConfig?: any;
    /**
     * 
     * @type {Array&lt;ConfigEntryTO&gt;}
     * @memberof ProcessConfigTO
     */
    configs?: any;
}
