/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ProcessInstanceInfoTO
 */
export interface ProcessInstanceInfoTO {
    /**
     * 
     * @type {string}
     * @memberof ProcessInstanceInfoTO
     */
    id: any;
    /**
     * 
     * @type {string}
     * @memberof ProcessInstanceInfoTO
     */
    processKey: any;
    /**
     * 
     * @type {string}
     * @memberof ProcessInstanceInfoTO
     */
    processName: any;
    /**
     * 
     * @type {string}
     * @memberof ProcessInstanceInfoTO
     */
    assignee: any;
    /**
     * 
     * @type {string}
     * @memberof ProcessInstanceInfoTO
     */
    status: any;
    /**
     * 
     * @type {string}
     * @memberof ProcessInstanceInfoTO
     */
    description: any;
    /**
     * 
     * @type {string}
     * @memberof ProcessInstanceInfoTO
     */
    statusKey: any;
    /**
     * 
     * @type {Date}
     * @memberof ProcessInstanceInfoTO
     */
    startTime?: any;
    /**
     * 
     * @type {Date}
     * @memberof ProcessInstanceInfoTO
     */
    endTime?: any;
}
