/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface RuleTO
 */
export interface RuleTO {
    /**
     * 
     * @type {string}
     * @memberof RuleTO
     */
    type?: any;
    /**
     * 
     * @type {string}
     * @memberof RuleTO
     */
    value?: any;
    /**
     * 
     * @type {string}
     * @memberof RuleTO
     */
    target?: any;
}
